### ISSUE TITLE
Secrets list using the hcp_vault_secrets_app datasource has only first 10 secrets

### ISSUE THREAD

**Issue by Suloch** [hashicorp/terraform-provider-hcp#1111]
### Terraform Version and Provider Version

```
Terraform version: v1.7.0
HCP provider version: v0.94.1
```

### Affected Resource(s)

* hcp_vault_secrets_app

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
terraform {
  required_providers {
    hcp = {
        source = "hashicorp/hcp"
        version = "0.94.1"
    }
  }
}

provider "hcp" {
  project_id = "..."
  client_id = "..."
  client_secret = "..."
}

data "hcp_vault_secrets_app" "test_app" {
  app_name = "Test-app"

}

output "secrets" {
  value = data.hcp_vault_secrets_app.test_app.secrets
  sensitive = true
}
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/Suloch/b7270436d32189505918aa7bcdfb4249
### Steps to Reproduce

1. Create an app with more than 10 entries
2. Create configuration to read the secrets from app like above
3.  `terraform apply -auto-approve && terraform output -json`

### Expected Behavior

There should be 12 secrets listed for this app. This was verified by the hcp bash client using `hcp vault-secrets secrets list`
Secret Name   Latest Version   Created At                 Type
KEY0          1                2024-10-07T14:48:38.563Z   kv  
KEY1          1                2024-10-07T14:48:38.743Z   kv  
KEY10         1                2024-10-07T14:48:38.936Z   kv  
KEY11         1                2024-10-07T14:48:38.774Z   kv  
KEY2          1                2024-10-07T14:48:38.805Z   kv  
KEY3          1                2024-10-07T14:48:38.405Z   kv  
KEY4          1                2024-10-07T14:48:38.918Z   kv  
KEY5          1                2024-10-07T14:48:38.572Z   kv  
KEY6          1                2024-10-07T14:48:38.752Z   kv  
KEY7          1                2024-10-07T14:48:38.774Z   kv  
KEY8          1                2024-10-07T14:48:38.774Z   kv  
KEY9          1                2024-10-07T14:48:38.878Z   kv 
### Actual Behavior
ata.hcp_vault_secrets_app.test_app: Reading...
data.hcp_vault_secrets_app.test_app: Read complete after 0s [id=Test-app]

Changes to Outputs:
  + secrets = (sensitive value)

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

secrets = <sensitive>
{
  "secrets": {
    "sensitive": true,
    "type": [
      "map",
      "string"
    ],
    "value": {
      "KEY0": "VALUE0",
      "KEY1": "VALUE1",
      "KEY10": "VALUE10",
      "KEY11": "VALUE11",
      "KEY2": "VALUE2",
      "KEY3": "VALUE3",
      "KEY4": "VALUE4",
      "KEY5": "VALUE5",
      "KEY6": "VALUE6",
      "KEY7": "VALUE7"
    }
  }
}

### Important Factoids

No.
### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jamtartley** [comment]
Also experiencing this - I can see in the audit log that the scope of the request changed from `APP_NAME 14 secrets` to `APP_NAME 10 secrets` roughly a month ago

**Comment by maxcoulombe** [comment]
Hello, thanks for bringing this up. The team has been working on the pagination of certain endpoints lately so it looks like not all clients like the HCP Terraform Provider were adjusted accordingly.

Sorry for the inconvenience, I'll raise this with the team. It should be an easy fix.

**Comment by divyapola5** [comment]
Hello, upgrading to version v0.97.0 should fix this issue. Thank you.
