### ISSUE TITLE
HCP Consul CA is not usable with Consul provider

### ISSUE THREAD

**Issue by nadenf** [hashicorp/terraform-provider-hcp#123]
### Terraform Version and Provider Version

```
0.15.3
```

### Affected Resource(s)

hcp_consul_cluster

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.15.3"
  required_providers {
    consul = {
      source  = "hashicorp/consul"
      version = "~> 2.12.0"
    }

    hcp = {
      source  = "hashicorp/hcp"
      version = "~> 0.6.0"
    }
  }
}


provider "consul" {
  address    = local.hashicorp_cloud.consul_url
  token      = local.hashicorp_cloud.consul_root_token_id
  ca_pem     = hcp_consul_cluster.consul.consul_ca_file
}
```
### Expected Behavior

You should be able to pass the HCP consul_ca_file output into the Consul provider input.

### Actual Behavior

You get the following error message: 

```
│ Error: failed to create http client: Error appending CA: Couldn't parse PEM
```

**Comment by bcmdarroch** [comment]
Hi @nadenf! Thanks for adding this issue. I'll bring this request up to our cloud Consul team and provide an update when I hear from them.

**Comment by bcmdarroch** [comment]
Got some guidance from the Consul team. Could you try decoding the CA file with this helper and let us know if that works? https://www.terraform.io/docs/language/functions/base64decode.html

**Comment by nadenf** [comment]
Is it worth revisiting why it is base64 encoded ?

If the Consul provider is expecting it to be PEM encoded then why not just make it simpler for everyone.

**Comment by nadenf** [comment]
@bcmdarroch  .. It also fails when base64 decoded.

```
Error: Failed to list Consul keys under prefix 'harana/cicd': Get "https://consul.consul.6b287e47-e880-4af5-b1e0-db844115eec4.aws.hashicorp.cloud/v1/kv/harana/cicd?recurse=": x509: certificate signed by unknown authority
```

Can see from the state file that the value is properly set i.e. it is a valid PEM (starts with BEGIN CERTIFICATE).

**Comment by chapmanc** [comment]
Hi @nadenf ! 

I am very sorry for not responding sooner.  

Just to clarify the  `hcp_consul_cluster.consul.consul_ca_file` you are reference in your terraform is the CA for consul agents to connect to the gRPC api. 

The consul provider only uses the http api. For HCP consul uses a Let's Encrypt certificate that will be valid. One other thing to consider is if your cluster is public or private. 

- If this is a private cluster you will need to run this terraform inside an ec2 instance that has a peered VPC with the HCP consul cluster's HVN. In this case the address would be `hcp_consul_cluster.consul_private_endpoint_url` field.
- If this is a public cluster you will be able to simply run this terraform anywhere and the address would be `hcp_consul_cluster. consul_public_endpoint_url`

Let me know if that helps clarify your workflow.

**Comment by yuritaco** [comment]
Based on @chapmanc's response, we are going to close this issue. Please let us know if you have further questions or comments!
