### ISSUE TITLE
HCP Consul Token is not usable with Consul provider 

### ISSUE THREAD

**Issue by nadenf** [hashicorp/terraform-provider-hcp#131]
### Terraform Version and Provider Version

```
0.15.3
```

### Affected Resource(s)

hcp_consul_cluster

### Terraform Configuration Files

```hcl
resource "hcp_consul_cluster" "example" {
  cluster_id = "consul-cluster"
  hvn_id     = hcp_hvn.example.hvn_id
  tier       = "development"
}

provider "consul" {
  address    = "demo.consul.io:80"
  token      = ???
}
```
### Expected Behavior

You should be able to pass the HCP Consul root token into the Consul Provider.

### Actual Behavior

There is only consul_root_token_accessor_id and consul_root_token_secret_id outputs from hcl_consul_cluster.

You can regenerate the token using hcp_consul_cluster_root_token but only kubernetes_secret is output.

**Comment by bcmdarroch** [comment]
Hi @nadenf! You should be able to use `consul_root_token_secret_id` as the value for `token` in the Consul provider config.

However, this will not work if you also have an `hcp_consul_cluster_root_token`. If you use the root token resource, you'll need to use its `secret_id` output in the Consul provider config.

**Comment by nadenf** [comment]
This is bizarre to name an id field as your actual token value but okay.

Worth updating documentation on the HCP Consul provider page to mention this ?

**Comment by bcmdarroch** [comment]
Documentation has been updated, so closing this issue.
