### ISSUE TITLE
Enable admin app role to prevent unnecessary increases in client count

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [hashicorp/terraform-provider-hcp#141]
### Description

Currently (unless I am misunderstanding something, which is totally possible) when a user spins up a vault instance in HCP, they need to issue an`hcp_vault_cluster_admin_token` in order to connect to their Vault via Terraform provider.  

However, this admin token (being not associated with an entity) leads to an ever increasing client count each time a new token is issued on refresh (every 6 hours I believe).  Since Vault billing goes up with client count, this feels like a rather unfortunate situation to put users in.  

It seems like there should be a pure IaC approach to providing users with some kind of "admin" identity out of the gate to prevent unnecessary client billing.  

### New or Affected Resource(s)

* hcp_0.6.0

### Potential Terraform Configuration

A total spitball would be something like this that would allow for Terraform to maintain an administrative role over the Vault, without increasing client count on plan/apply/etc when the admin token has expired. 

```hcl
resource "hcp_vault_cluster" "bkbn" {
  cluster_id = "bkbn"
  hvn_id = hcp_hvn.bkbn.hvn_id
  public_endpoint = true
  enable_admin_app_role = true // this line 
}

// At which point something like this could be used to authenticate to the vault provider
resource "hcp_vault_cluster_admin_role" "admin" {
  cluster_id = hcp_vault_cluster.example_vault_cluster.cluster_id
}
```

### References

N/A 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcmdarroch** [comment]
Thanks for submitting this issue @rgbrizzlehizzle! I'll bring this up with our Vault cloud team and see what we can do.

**Comment by bcmdarroch** [comment]
To provide a quick update: Cloud Vault team is planning to mitigate this issue by ensuring that admin tokens won’t add additional cost per refreshed token.

**Comment by rgbrizzlehizzle** [comment]
That'll do the trick
