### ISSUE TITLE
Support non development type vault clusters

### ISSUE THREAD

**Issue by wagnst** [hashicorp/terraform-provider-hcp#143]
As per latest doc https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/resources/vault_cluster
there is no option to provision non development type clusters. But as per HCP console there is:

Standard tier and cluster size choosers.

![grafik](https://user-images.githubusercontent.com/7312523/121545942-3c4c0c80-ca0b-11eb-9fb8-b2bc8fe7faf8.png)

I couldnt find such options in the provider! Please add support for it.

**Comment by waxb** [comment]
https://github.com/hashicorp/terraform-provider-hcp/pull/144
Will check how the Consul part is implemented

**Comment by bcmdarroch** [comment]
Vault cluster tiers have been released in [v0.8.0](https://github.com/hashicorp/terraform-provider-hcp/releases/tag/v0.8.0)
