### ISSUE TITLE
Unexpected "unable to fetch organization list"

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [hashicorp/terraform-provider-hcp#172]
Little bit of context here, I've been running the HCP provider since.... 0.6? Anyway currently on 0.8 and everything has been fine and dandy, and out of the blue today I get hit with this error, no infra code has changed since my last deploy so this is super odd.  

### Terraform Version and Provider Version

```
Terraform version: 1.0
HCP provider version: 0.8.0 and 0.10.0
```

### Affected Resource(s)

provider / initialization

### Terraform Configuration Files

```hcl
provider "hcp" {
  client_id     = var.hcp_client_id
  client_secret = var.hcp_client_secret
}
```

### Debug Output

Omitting unless really necessary 

### Steps to Reproduce

1. `terraform plan`

### Expected Behavior

Happy deploy that has been happening for months before now 

### Actual Behavior

Angry deploy that complains 

```
╷
│ Error: unable to fetch organization list: &{0 []  } (*models.GrpcGatewayRuntimeError) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface
│
│   with module.hcp.provider["registry.terraform.io/hashicorp/hcp"],
│   on modules/hcp/phase_3.tf line 19, in provider "hcp":
│   19: provider "hcp" {
│
╵
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rgbrizzlehizzle** [comment]
Ah I was just checking in on https://status.hashicorp.com/ and it looks like an upgrade is in process, hopefully there is just some weirdness there and this goes away once that upgrade is complete :)

**Comment by bcmdarroch** [comment]
Migration complete! Are you still experiencing this issue?

**Comment by rgbrizzlehizzle** [comment]
Yep looks like it's fixed, gonna close
