### ISSUE TITLE
Feature gap for Vault support

### ISSUE THREAD

**Issue by wagnst** [hashicorp/terraform-provider-hcp#231]
It seems this provider especially for Vault is really unmaintained at the moment.

You are releasing lots of features for Vault (metrics streaming, etc.) but none of them are implemented here.

How can this be adressed? Its frustrating.

**Comment by bcmdarroch** [comment]
Thanks for submitting this issue. We apologize for the frustration. We are working on addressing this gap.

**Comment by iiro** [comment]
Completely agree with @wagnst on this. It's shameful this is still open after 4 months from opening the issue.

**Comment by bcmdarroch** [comment]
We apologize for the frustration. I've received an update that metrics streaming is planned for this quarter.

**Comment by iiro** [comment]
Thanks for the update @bcmdarroch. Looking forward for this!

**Comment by bcmdarroch** [comment]
Metrics streaming added in: https://github.com/hashicorp/terraform-provider-hcp/pull/319
