### ISSUE TITLE
hcp_vault_cluster - support for resizing cluster

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-provider-hcp#257]
### Terraform Version and Provider Version

```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/hcp v0.22.0
```

### Affected Resource(s)

* hcp_vault_cluster

### Terraform Configuration Files

first:
```hcl
resource "hcp_vault_cluster" "example" {
  cluster_id = "vault-cluster"
  hvn_id     = hcp_hvn.example.hvn_id
  tier       = "standard_small"
}
```
then:

```hcl
resource "hcp_vault_cluster" "example" {
  cluster_id = "vault-cluster"
  hvn_id     = hcp_hvn.example.hvn_id
  tier       = "standard_medium"
}
```

### Debug Output

https://gist.github.com/assareh/df008a15b5ef883ebd7e953f41f94926

### Steps to Reproduce

1. Provision a standard cluster.
2. Change the tier to another size of standard cluster and `terraform apply`

### Expected Behavior

The cluster should have been resized. This operation is allowed on standard tier clusters when performed in the HCP console. 

### Actual Behavior

An error occurred.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcmdarroch** [comment]
This functionality has been made available in v0.24.0! 🎉 
https://github.com/hashicorp/terraform-provider-hcp/releases/tag/v0.24.0
