### ISSUE TITLE
Add metrics and audit log streaming for Vault

### ISSUE THREAD

**Issue by phclark** [hashicorp/terraform-provider-hcp#297]
### Description

It would be great to be able to configure metric and audit log streaming via Terraform, similar to how we configure the rest of HCP. This would enable API keys, passwords, etc., to be sourced from places like Vault allowing for centralized secret rotation. 

### New or Affected Resource(s)

New resources could be:
* hcp_vault_metrics_stream
* hcp_vault_audit_log_stream

### Potential Terraform Configuration

```hcl
resource "hcp_vault_metrics_stream" "this" {
  metrics_provider = "datadog"
  datadog_api_key = "..."
  datadog_site_region = "us1"
}

resource "hcp_vault_audit_log_stream" "this" {
  log_provider = "datadog"
  datadog_api_key = "..."
  datadog_site_region = "us1"
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcmdarroch** [comment]
Thanks for writing up this issue! The HCP Vault team has this work planned and hopes to deliver it soon.

**Comment by iniinikoski** [comment]
Hi! :) Just noticed that this was just released in this: https://github.com/hashicorp/terraform-provider-hcp/pull/319

A quick comment: as we are using the EU region, a note that we also have to define "eu1" as a "datadog_region" (not just EU). Just a small confusion in here as it's the first time we have to add the number there. But it's documented in here: https://docs.datadoghq.com/getting_started/site/ - if anyone else also bumps into this. :)

**Comment by bcmdarroch** [comment]
Added in: https://github.com/hashicorp/terraform-provider-hcp/pull/319
