### ISSUE TITLE
HCP Consul Cluster failed to launch

### ISSUE THREAD

**Issue by webdog** [hashicorp/terraform-provider-hcp#335]
>  Error: unable to create Consul cluster (): create Consul cluster operation () failed [code=13, message=failed to deploy consul cluster: failed to provision Consul cluster: rpc error: code = Internal desc = error applying Terraform: Provider produced inconsistent result after apply  When applying changes to aws_iam_role.doormat_ssh, provider "registry.terraform.io/-/aws" produced an unexpected new value for was present, but now absent.  This is a bug in the provider, which should be reported in the provider's own issue tracker.]

<img width="2229" alt="image" src="https://user-images.githubusercontent.com/960210/174849292-6ebb95ad-24e5-418d-916d-742b29f2b477.png">

Unable to import the resource into the project:

 ```shell
$ terraform import module.tutorial_infrastructure.module.resources.hcp_consul_cluster.server 
module.tutorial_infrastructure.module.resources.hcp_consul_cluster.server: Importing from ID ""...
module.tutorial_infrastructure.module.resources.hcp_consul_cluster.server: Import prepared!
  Prepared hcp_consul_cluster for import
module.tutorial_infrastructure.module.resources.hcp_consul_cluster.server: Refreshing state... [id=//hashicorp.consul.cluster/]
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "module.tutorial_infrastructure.module.resources.hcp_consul_cluster.server", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it
│ is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
╵
```

**Comment by webdog** [comment]
This is a bit of a flow-breaking/less than great UX. Because the cluster is in this nebulous state, I have to manually delete this cluster from the UI, and then run terraform destroy, as I don't trust the state of the infrastructure after this failure.

Since the HCP Consul Cluster with the HVN can take 15-30 minutes in some cases, this is a bit of a time sink. 😢

**Comment by jjtimmons** [comment]
@webdog in terms of the failure root cause, we're going to work on a fix shortly. Thank you for reporting

> error applying Terraform: Provider produced inconsistent result after apply
