### ISSUE TITLE
hcp_azure_peering_connection Data Source times out too soon

### ISSUE THREAD

**Issue by crhino** [hashicorp/terraform-provider-hcp#377]
### Terraform Version and Provider Version

```
Terraform version: v1.0.11
HCP provider version: v0.41.0
```

### Affected Resource(s)

* hcp_azure_peering_connection

### Terraform Configuration Files

```hcl
data "hcp_azure_peering_connection" "peering" {
  hvn_link              = var.hvn.self_link
  peering_id            = hcp_azure_peering_connection.peering.peering_id
  wait_for_active_state = true
}
```

### Steps to Reproduce

1. `terraform apply`
2. Occasionally HCP Azure peering connection takes a long time to get into `ACTIVE` state

### Expected Behavior

I expect the `hcp_azure_peering_connection` to keep retrying until it reaches the defined timeout, 35 minutes.

### Actual Behavior

The `hcp_azure_peering_connection` always times out after 20 minutes, even if we set a lower bound timeout of `1m` explicitly in the Terraform file.

### References

I believe the issue might be in the Terraform SDK, and have opened an issue there: https://github.com/hashicorp/terraform-plugin-sdk/issues/1038

I am writing this issue to track it explicitly for the HCP terraform provider.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcmdarroch** [comment]
Thanks for investigating this! I'll follow up with the plugin SDK team and see if we can get a fix for the upstream bug.

**Comment by bcmdarroch** [comment]
Resolved by https://github.com/hashicorp/terraform-provider-hcp/pull/389 using workaround suggested in https://github.com/hashicorp/terraform-plugin-sdk/pull/1041
