### ISSUE TITLE
Resources defined wrongly

### ISSUE THREAD

**Issue by raylaijh** [hashicorp/terraform-provider-hcp#387]
### Terraform Version and Provider Version

```
Terraform version: v1.2.2
HCP provider version: v0.43.0
```

### Affected Resource(s)

* hcp_hvn_route

### Terraform Configuration Files

```hcl
resource "hcp_hvn_route" "example" {
  hvn_link         = hcp_hvn.hvn.self_link
  hvn_route_id     = var.route_id
  destination_cidr = aws_vpc.peer.cidr_block
  target_link      = data.hcp_aws_network_peering.example.self_link
}
```

### Debug Output
╷
│ Error: Reference to undeclared resource
│
│   on main.tf line 60, in resource "hcp_hvn_route" "example":
│   60:   hvn_link         = hcp_hvn.hvn.self_link
│
│ A managed resource "hcp_hvn" "hvn" has not been declared in the root module.
╵

### Steps to Reproduce

1. Followed code example based on https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/guides/peering
2. `terraform apply` and error occurs

### Expected Behavior

1. `terraform apply` is successful

### Actual Behavior

1. `terraform apply` and error occurs

### Important Factoids

1. resource name with hvn under hcp_hvn does not exist

Line 60 should be changed from

```hcl
hvn_link         = hcp_hvn.hvn.self_link
```
to 

```hcl
hvn_link         = hcp_hvn.example.self_link
```
since _example_ is the name of configured for hcp_hvn in the example code instead of _hvn_.

### References

* https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/guides/peering

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by JolisaBrownHashiCorp** [comment]
@raylaijh Thanks for the suggested fix! We've opened [a PR](https://github.com/hashicorp/terraform-provider-hcp/pull/388) for the doc update, and it will be merged in the next provider release. :tada:
