### ISSUE TITLE
`error updating Vault cluster` when trying to increase tier size

### ISSUE THREAD

**Issue by unredundant** [hashicorp/terraform-provider-hcp#398]
### Terraform Version and Provider Version

```
Terraform version: 1.3.0
HCP provider version: 0.43.0
```

### Affected Resource(s)

* hcp_vault_cluster

### Terraform Configuration Files

```hcl
resource "hcp_hvn" "omit" {
  hvn_id         = "omit"
  cloud_provider = "aws"
  region         = "us-east-1"
  cidr_block     = "omit"
}

resource "hcp_vault_cluster" "omit" {
  cluster_id      = "omit"
  hvn_id          = hcp_hvn.omit.hvn_id
  public_endpoint = true
  tier = "starter_small" // Changed this from empty (dev) to starter_small
}

resource "hcp_vault_cluster_admin_token" "omit" {
  cluster_id = hcp_vault_cluster.omit.cluster_id
}
```

### Debug Output

╷
│ Error: error updating Vault cluster (omit): [PATCH /vault/2020-11-25/organizations/{cluster.location.organization_id}/projects/{cluster.location.project_id}/clusters/{cluster.id}][403] Update default  &{Code:7 Details:[] Error: Message:}
│ 
│   with module.hcp.hcp_vault_cluster.omit,
│   on modules/hcp/hcp.tf line 8, in resource "hcp_vault_cluster" "omit":
│    8: resource "hcp_vault_cluster" "omit" {
│ 
╵

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by paraspraj** [comment]
Hey @unredundant! 👋🏽  Would you mind sharing more of the error message that you're getting? I've run this locally and created a default tier Vault cluster then updated it to `starter_small` but did not come across the same error as you. It updated the Vault cluster successfully. 
I'm running the same Terraform version as you (1.3.0) but I'm using 0.45.0 of the HCP Provider. If possible, are you able to run your command with the updated HCP Provider as well?

**Comment by unredundant** [comment]
Oh... yea the the HCP access/secret pair I generated is a contributor, not an admin.  Good call 👍

**Comment by iniinikoski** [comment]
Ouch... Sorry for commenting a closed issue but, just bumped into this as well - and was puzzled what's happening. Please @paraspraj document this down into the the resource that changing the tier will require an "admin". This will bite to people for sure...

**Comment by paraspraj** [comment]
Thanks for the suggestion @iniinikoski! You should see these changes once the next release of the Terraform Provider comes out 👍🏽 
https://github.com/hashicorp/terraform-provider-hcp/pull/400
