### ISSUE TITLE
Documentation for the browser OIDC login support

### ISSUE THREAD

**Issue by tmatilai** [hashicorp/terraform-provider-hcp#409]
### Description

I just accidentally discovered that the provider automatically spins up a browser based OIDC login flow to authenticate against HCP if the `client_id` and `client_secret` are no specified (as I forgot to set the env vars in a new module). That's great as it avoids the need for shared secrets in some cases!

The feature seems to have landed in SDK v0.22.0 with https://github.com/hashicorp/hcp-sdk-go/pull/112, and in v0.45.0 of the provider.

Assuming this is a supported feature, it would be good to update the provider documentation.
(Writing docs is hard for me, so I won't volunteer 🙈 )

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by JolisaBrownHashiCorp** [comment]
Thank you for sharing this enhancement suggestion. We are currently updating our docs to better showcase this feature and will have them included in the provider shortly!

**Comment by bcmdarroch** [comment]
https://github.com/hashicorp/terraform-provider-hcp/releases/tag/v0.49.0
