### ISSUE TITLE
docs: `hcp_consul_cluster_root_token` and `hcp_consul_cluster` management tokens

### ISSUE THREAD

**Issue by joshRooz** [hashicorp/terraform-provider-hcp#420]
### Terraform Version and Provider Version

```
Terraform version: 1.3.5
HCP provider version: 0.49.0
```

### Affected Resource(s)

* hcp_consul_cluster
* hcp_consul_cluster_root_token

### Expected Behavior

Per `hcp_consul_cluster_root_token` resource [documentation](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/resources/consul_cluster_root_token): 
> "Note that creation of this resource will invalidate the default consul_root_token_accessor_id and consul_root_token_secret_id on the target hcp_consul_cluster resource."

I am expecting the root token created by the `hcp_consul_cluster` resource to be invalidated/deleted after `hcp_consul_cluster_root_token` is created.

### Actual Behavior

Following `hcp_consul_cluster` and `hcp_consul_cluster_root_token` resource creation, `consul acl token list` returns two management tokens.

### Important Factoids

I bootstrapped the HCP Consul cluster yesterday and used the `hcp_consul_cluster.example.consul_root_token_secret_id` to configure the consul provider then perform additional config/setup tasks.

~24 hours later I added `hcp_consul_cluster_root_token` and ran another `terraform apply`. 

If there is a clean-up or reconciliation job that runs in the background, I'm unclear when/if that will be triggered and what the qualification criteria is. 

My intention is to manage the lifecycle of a root token independently from the `hcp_consul_cluster` resource. Leveraging the `hcp_consul_cluster_root_token` resource to decouple the root/bootstrap token from the consul cluster lifecycle appears to be clean a way to accomplish that, but I want to ensure that I'm not leaving any management tokens laying around.

```sh
consul acl token list

AccessorID:       c00576dc-603d-ad10-6a7c-dc18c159336b
SecretID:         <redacted>
Partition:        default
Namespace:        default
Description:      
Local:            false
Create Time:      2022-11-21 19:59:36.785458507 +0000 UTC
Legacy:           false
Policies:
   00000000-0000-0000-0000-000000000001 - global-management

AccessorID:       480937ce-0a8d-53c2-d88c-5dc08baee335
SecretID:         <redacted>
Partition:        default
Namespace:        default
Description:      
Local:            false
Create Time:      2022-11-22 22:49:26.228086185 +0000 UTC
Legacy:           false
Policies:
   00000000-0000-0000-0000-000000000001 - global-management
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by crhino** [comment]
Closed by #439
