### ISSUE TITLE
Error when using non-prod HCP environment

### ISSUE THREAD

**Issue by NickCellino** [hashicorp/terraform-provider-hcp#442]
### Terraform Version and Provider Version

```
Terraform version: v1.3.7
HCP provider version: v0.52.0
```

### Affected Resource(s)

* authentication

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    hcp = {
      source  = "hashicorp/hcp"
      version = "= 0.52.0"
    }
  }
}

// Configure the provider
provider "hcp" {}


// Create an HVN
resource "hcp_hvn" "example_hvn" {
  hvn_id         = "hcp-tf-example-hvn"
  cloud_provider = "aws"
  region         = "us-west-2"
  cidr_block     = "172.25.16.0/20"
}
```

### Debug Output

https://gist.github.com/NickCellino/def8ecd610ef52df17f290d50733ce64

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

1. HVN is created

### Actual Behavior

1. I received the following error message:

```
Error: unable to get project from credentials: unable to fetch organization list: Could not complete request. Please ensure your HCP_API_HOST, HCP_CLIENT_ID, and HCP_CLIENT_SECRET are correct.
```

### Important Factoids

This works correctly if I pin the hcp provider version to `0.44.0` but if I do `0.45.0` or anything after that, I get the error.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcmdarroch** [comment]
This is related to an internal breaking change released in https://github.com/hashicorp/hcp-sdk-go/releases/tag/v0.22.0. This [internal doc](https://backstage.hashicorp.services/docs/default/Component/cloud-experiences-tooling-docs/go-sdk/environments/) has the information needed to resolve the issue.
