### ISSUE TITLE
Terraform Provider Plugin Crashed

### ISSUE THREAD

**Issue by jpapazian2000** [hashicorp/terraform-provider-hcp#496]
### Terraform Version and Provider Version

```
Terraform version: 1.4.4
HCP provider version: 0.56.0
```

### Affected Resource(s)

* hcp_XXXXX

### Terraform Configuration Files

```hcl
# create ec2 instance
data "hcp_packer_iteration" "ubuntu-apache" {
  bucket_name = "ubuntu-apache-aws"
  channel = "latest"
}
data "hcp_packer_image" "ubuntu-apache-aws" {
  bucket_name     = "ubuntu-apache-aws"
  channel         = "latest"
  cloud_provider  = "aws"
  region          = "eu-west-3"
}
resource "random_integer" "num" {
  min = 0
  max = local.subnet_count - 1
}

resource "aws_instance" "web_host" {
  ami                    = data.hcp_packer_image.ubuntu-apache-aws.cloud_image_id
  instance_type          = var.instance_type
  vpc_security_group_ids = [aws_security_group.web-node.id]
  subnet_id              = aws_subnet.web_subnet[local.az_num].id

  tags = {
    
      Name        = "${local.resource_prefix}-ec2"
      Environment = var.environment
      ttl = "24h"
      owner = var.owner
      region = var.region
      purpose = "test something fashion"
      atemi = var.atemi
    }
  
  monitoring = true
  ebs_optimized = true
  root_block_device {
    encrypted = true
  }

  lifecycle {
      postcondition {
        condition = self.instance_type == "t3.large"
        error_message = "The selected instance type is to big for this usage"
      }

      postcondition {
        condition = self.tags["purpose"] == "test something fashion"
        error_message = "The selected instance type is to big for this usage"
      }
      postcondition {
        condition = self.ami == data.hcp_packer_image.ubuntu-apache-aws.cloud_image_id
        error_message = "you don't use the latest available image data.hcp_packer_image.worker.cloud_image_id"
      }
    }
}
```

### Debug Output

Error: Plugin did not respond
with data.hcp_packer_iteration.ubuntu-apache
on main.tf line 13, in data "hcp_packer_iteration" "ubuntu-apache":
data "hcp_packer_iteration" "ubuntu-apache" {
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.

### Panic Output

https://gist.github.com/jpapazian2000/0052fd96b46333181b1af9fa5e929073

### Steps to Reproduce

 - create an ubuntu ami
 -  create an hcp packer bucket
 - create an iteration
 - use the above terraform code to provision the ami
I note that if I revoke the iteration, then I get the above crash in terraform, while I do not get the crash when the iteration is not present

### Expected Behavior

with the iteration revoked tfcb should have returned a message saying it can provision the ami as it is revoked

### Actual Behavior

crash

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aidan-mundy** [comment]
Thanks for reporting this issue!

Provider version v0.62.0 includes a fix for `hcp_packer_iteration` causing the provider to panic when it is pointed to a channel that doesn't have an assigned iteration. It will still throw an error because there is no iteration found, but it is much more informative now. 

As a note, some revocation actions will cause a channel to rollback to a previous iteration or to have no assigned iteration, rather than leaving the channel assigned to a revoked iteration. This is an upstream behavior of HCP Packer and cannot be changed at this time. To revoke an iteration, but still keep it as the channel's assigned iteration, you can set the revocation time to a very short time in the future (like 1 or 2 minutes).
