### ISSUE TITLE
[Enhancement] Manager user access to Hashicorp Cloud Platform

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-hcp#507]
### Description

We would like to be able to manage user access to our HCP organization using terraform. 

### New or Affected Resource(s)

* hcp_iam_user

### Potential Terraform Configuration

```hcl
resource "hcp_iam_user" "drew" {
  email = "drew@ex.com"
  role = "admin"
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by drewmullen** [comment]
I'm happy to work on this if the team can point me to the APIs and will agree that this is a feature they want to support

**Comment by xargs-P** [comment]
Thank you for the PR! We are planning to have greater coverage for Identity within the terraform provider. As we are still in planning, I will close this PR as of right now. But we would like to take this as input into our planning for better coverage. Thank you again and please feel free to share more feedback for the team.

**Comment by pacoguzman** [comment]
@xargs-P I can see lately `hcp_organization` and `hcp_project` plus policies and binding resources were added. Are there any plan to keep increasing coverage for identity with `hcp_user` resources?
