### ISSUE TITLE
Add support for multiple organizations

### ISSUE THREAD

**Issue by chrisvanmeer** [hashicorp/terraform-provider-hcp#508]
### Description

Please add support for users that are part of more than one organization.  
The current provider does not support specifying an `org_id` so it seems.  
  
One would get an error during a `terraform plan` that outputs:

```hcl
╷
│ Error: unable to get project from credentials: unexpected number of organizations: expected 1, actual: 2
│ 
│   with provider["registry.terraform.io/hashicorp/hcp"],
│   on main.tf line 18, in provider "hcp":
│   18: provider "hcp" {}
│ 
```

This means I cannot use the HCP provider at all.

### New or Affected Resource(s)

* All

### Potential Terraform Configuration

```hcl
provider "hcp" {
  client_id     = "service-principal-key-client-id"
  client_secret = "service-principal-key-client-secret"
  org_id        = "organization-id"
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xargs-P** [comment]
Hello @chrisvanmeer , I am one of the Product Managers under Identity for HCP. I am curious about what you are looking to accomplish  🤔 . Would you be open to talking more? Feel free to contact me: tpowell #at# hashicorp.com

**Comment by chrisvanmeer** [comment]
Email is on the way!

**Comment by chrisvanmeer** [comment]
It seems that this issue has already been fixed since I have no problems deploying resources now.
