### ISSUE TITLE
bug: revoked iterations causes panic

### ISSUE THREAD

**Issue by lrstanley** [hashicorp/terraform-provider-hcp#526]
### Terraform Version and Provider Version

```
$ terraform -v
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.2.0
+ provider registry.terraform.io/hashicorp/hcp v0.60.0
```

### Affected Resource(s)

* `hcp_packer_image` data source

### Terraform Configuration Files

```hcl
provider "hcp" {}

provider "aws" {
  region = "us-east-1"
}

data "hcp_packer_image" "learn-packer-amazonlinux2" {
  bucket_name    = "learn-packer-amazonlinux2-child"
  channel        = "latest"
  cloud_provider = "aws"
  region         = "us-east-1"
}

output "hcp_packer_image" {
  value = data.hcp_packer_image.learn-packer-amazonlinux2
}
```

### Debug Output

[gist: terraform-hcp-packer-panic.txt](https://gist.githubusercontent.com/lrstanley/47e2fee0472c256128d6afbefcb63366/raw/fa8b9c5c80c67c8f7c8e9a7576dfd2cbc282e8d2/terraform-hcp-packer-panic.txt)

### Panic Output

```
data.hcp_packer_image.learn-packer-amazonlinux2: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│   with data.hcp_packer_image.learn-packer-amazonlinux2,
│   on main.tf line 7, in data "hcp_packer_image" "learn-packer-amazonlinux2":
│    7: data "hcp_packer_image" "learn-packer-amazonlinux2" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-hcp_v0.60.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xdec396]

goroutine 99 [running]:
github.com/hashicorp/terraform-provider-hcp/internal/provider.dataSourcePackerImageRead({0x1207608, 0xc000136b40}, 0x0?, {0xf06480?, 0xc0005a21a0})
        github.com/hashicorp/terraform-provider-hcp/internal/provider/data_source_packer_image.go:171 +0x5d6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000267c00, {0x1207640, 0xc0005171d0}, 0xd?, {0xf06480, 0xc0005a21a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000267c00, {0x1207640, 0xc0005171d0}, 0xc0005e9d00, {0xf06480, 0xc0005a21a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000280db0, {0x1207640?, 0xc0005170b0?}, 0xc00028aa40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1195 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000599f40, {0x1207640?, 0xc000516720?}, 0xc0005c9090)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1031540?, 0xc000599f40}, {0x1207640, 0xc000516720}, 0xc0001e68c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x120a5e0, 0xc0005829c0}, 0xc000026d80, 0xc0005956e0, 0x19b2610, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x120a5e0, 0xc0005829c0}, 0xc000026d80, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-hcp_v0.60.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. Create two versions of an image in HCP Packer. Revoke both of them.
2. Reference the bucket name that contains both revoked iterations.
3. `terraform plan`

### Expected Behavior

Would expect the plan to work as expected (as nothing is actually preventing a revoked iteration from being used).

### Actual Behavior

Panics.

### Important Factoids

If I un-revoke one of the iterations, it works without issue, which makes me believe it is directly related. See also:

![image](https://github.com/hashicorp/terraform-provider-hcp/assets/1847365/a7e6865d-1f0f-49d4-acf4-85c6e2659990)

### References

* May be related: https://github.com/hashicorp/terraform-provider-hcp/issues/496
* May be related: https://github.com/hashicorp/terraform-provider-hcp/issues/493

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aidan-mundy** [comment]
Thanks for reporting this issue!

Provider version v0.62.0 includes a fix for `hcp_packer_iteration` causing the provider to panic when it is pointed to a channel that doesn't have an assigned iteration. It will still throw an error because there is no iteration found, but it is much more informative now. 

As a note, some revocation actions will cause a channel to rollback to a previous iteration or to have no assigned iteration, rather than leaving the channel assigned to a revoked iteration. This is an upstream behavior of HCP Packer and cannot be changed at this time. To revoke an iteration, but still keep it as the channel's assigned iteration, you can set the revocation time to a very short time in the future (like 1 or 2 minutes).

In the example provided in this issue, the `latest` channel likely rolled back from `v2` to `v1`, and then to empty/unassigned. In that case, it is not possible to get the iteration with the data source, and the plan will still fail (now with a more graceful error after the fix mentioned above).
