### ISSUE TITLE
0.84.0 dropped the support for hcp_packer_iteration and hcp_packer_image. Shouldn't this be a Major release?

### ISSUE THREAD

**Issue by fernandoiury** [hashicorp/terraform-provider-hcp#798]
### Terraform Version and Provider Version

```
Terraform version: 1.6.6
HCP provider version: 0.84.0
```

### Affected Resource(s)

* hcp_packer_iteration
* hcp_packer_image

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    hcp = {
      source  = "hashicorp/hcp"
      version = "~> 0.49.0"
    }
  }
}

data "hcp_packer_iteration" "image" {
  bucket_name = "platform-${var.source_image_type}-base"
  channel     = local.hcp_packer_channel
}
 
data "hcp_packer_image" "image" {
  bucket_name    = "platform-${var.source_image_type}-base"
  cloud_provider = "gce"
  iteration_id   = data.hcp_packer_iteration.image[0].ulid
  region         = local.cis_images_region
}
```

### Steps to Reproduce

1. `terraform plan`
![image](https://github.com/hashicorp/terraform-provider-hcp/assets/10088173/6fe6aea2-22d2-44c8-9ae1-50ed40be398a)

### Expected Behavior
I'd expect that resources removal would be done via a Major release, not minor.

### Actual Behavior
0.83 had support for the resources
0.84 dropped the support

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pierluc-codes** [comment]
Hi @fernandoiury Sorry for the inconvenience. HashiCorp considers anything that is under version 1.0.0 unstable and can change at anytime. This inline with [Semantic Versioning 2.0.0](https://semver.org/#spec-item-4)

Again, sorry about the inconvenience.
