### ISSUE TITLE
hcp_group_members attribute mismatch

### ISSUE THREAD

**Issue by meetyingying** [hashicorp/terraform-provider-hcp#821]
in the [hcp provider documentation](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/resources/group_members), the example config code is:
```
resource "hcp_group_members" "example" {
  group = hcp_group.example.resource_name
  members = [
    hcp_user_principal.example1.id,
    hcp_user_principal.example2.id,
  ]
}
```

The [hcp_user_principals](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/data-sources/user_principal) only have user_id.

could you change `id` with `user_id` in the example?

**Comment by squaresurf** [comment]
This has been fixed in the v0.90.0 release. You can see that this is fixed on the latest version of the docs here: https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/resources/group_members
